algoritmo "ex-003"
// 03- Crie um programa que leia o nome e o salário
// de um funcionário, mostrando no final uma mensagem.
var
   nome: caractere
   sal: real
inicio
      escreva("Digite o nome do Funcionario: ")
      leia(nome)
      escreva("Digite o salario do Funcionario ",nome," R$")
      leia(sal)
      escreva("O Funcionario ",nome," atualmente recebe o salario de:",sal,"R$")
fimalgoritmo