algoritmo "ex-042"
//Faça um algoritmo que pergunte ao usuário um número inteiro e positivo
//qualquer e mostre uma contagem até esse valor:
var
         num,contador: inteiro
inicio
      Escreva("Digite um numero POSITIVO inteiro, vou contar ate ele! ")
      leia(num)
      contador <- 1
      Enquanto (contador <= num) faca
          escreval(contador)
          contador <- contador + 1
      FimEnquanto
      Escreval("Terminei!!")
      Escreval(")o)woooooh (o(")
fimalgoritmo