algoritmo "ex-009"
//Faça um algoritmo que leia quanto dinheiro uma pessoa tem na carteira (em R$)
//e mostre quantos dólares ela pode comprar. Considere US$1,00 = R$4,85.
var
   dinheirao,dolores: real
inicio
      Escreva(" Quantos reaizinhos na carteira patrão? ")
      leia(dinheirao)
      dolores <- dinheirao/4,85
      escreva(" Com ",dinheirao,"R$ Tu pode comprar ",dolores,"U$ em doletas.")
fimalgoritmo