algoritmo "Enquanto"
"Estruturas de Repetição"
var
   maior,s,n,cont: inteiro
inicio
      cont <- 1
      s <- 0
      Enquanto (cont <= 5) faca
        escreva("Digite o ", cont, "o. valor: ")
        leia(N)
        s <- s + n
        cont <- cont + 1
        Se(n >= maior)entao
             maior <- n
        Fimse
      FimEnquanto
      Escreval("A soma de todos os valores foi ", s, " E o maior numero foi: ",maior)
fimalgoritmo